spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    secure-port-enabled: true
    non-secure-port-enabled: false
  client:
    register-with-eureka: false
    fetch-registry: false